<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <RootNamespace>AIInterviewSimulator.Engine</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\AIInterviewSimulator.Data\AIInterviewSimulator.Data.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Google_GenerativeAI" Version="3.6.7" />
    </ItemGroup>

</Project>
